version: '3'
services:
  api:
    build:
      dockerfile: docker/FalconDockerfile
      context: .
    ports:
      - "9001:9001"
    volumes:
      - .:/usr/src/app
    environment:
      - FALCON_SETTINGS_MODULE=pozetron_barcode.settings.docker
