version: '3'
services:
  redis:
    image: redis
    hostname: redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - ./data:/redis-data
    restart: always
  api:
    build:
      dockerfile: docker/FalconDockerfile
      context: .
    ports:
      - "9001:9001"
    volumes:
      - .:/usr/src/app
    links:
      - redis
    env_file:
      - .env
